resources:
- name: cf-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-release.git
    branch: release-candidate

- name: postgres-release-develop
  type: git
  source:
    uri: https://github.com/cloudfoundry/postgres-release.git
    branch: upgrade-pipeline

jobs:
- name: upload-stemcells-releases
  plan:
  - aggregate:
    - get: cf-release
      attempts: 3
    - get: postgres-release
      resource: postgres-release-develop
  - task: upload-stemcell-fresh
    file: postgres-release/ci/scripts/upload-stemcell/task.yml
    params: &bosh_params_fresh
      BOSH_DIRECTOR: {{fresh_bosh_director}}
      BOSH_USER: {{fresh_bosh_user}}
      BOSH_PASSWORD: {{fresh_bosh_password}}
      BOSH_PUBLIC_IP: {{fresh_bosh_public_ip}}
  - task: upload-stemcell-old
    file: postgres-release/ci/scripts/upload-stemcell/task.yml
    params: &bosh_params_old
      BOSH_DIRECTOR: {{old_bosh_director}}
      BOSH_USER: {{old_bosh_user}}
      BOSH_PASSWORD: {{old_bosh_password}}
      BOSH_PUBLIC_IP: {{old_bosh_public_ip}}
  - task: upload-stemcell-older
    file: postgres-release/ci/scripts/upload-stemcell/task.yml
    params: &bosh_params_older
      BOSH_DIRECTOR: {{older_bosh_director}}
      BOSH_USER: {{older_bosh_user}}
      BOSH_PASSWORD: {{older_bosh_password}}
      BOSH_PUBLIC_IP: {{older_bosh_public_ip}}
  - task: create-postgres-dev-release-tarball
    file: postgres-release/ci/scripts/create-dev-release-tarball/task.yml
    input_mapping: {dev-release: postgres-release}
    output_mapping: {dev-release-tarball: postgres-tarball}
    params:
      <<: *bosh_params_fresh
      REL_NAME: postgres
      REL_VERSION: v999+dev.1
  - task: create-cf-dev-release-tarball
    file: postgres-release/ci/scripts/create-dev-release-tarball/task.yml
    input_mapping: {dev-release: cf-release}
    output_mapping: {dev-release-tarball: cf-tarball}
    params:
      <<: *bosh_params_fresh
      REL_NAME: cf
      REL_VERSION: v999+dev.1
  - task: upload-postgres-dev-releases-fresh
    file: postgres-release/ci/scripts/upload-dev-release-tarball/task.yml
    input_mapping: {dev-release-tarball: postgres-tarball}
    params:
      <<: *bosh_params_fresh
  - task: upload-cf-dev-releases-fresh
    file: postgres-release/ci/scripts/upload-dev-release-tarball/task.yml
    input_mapping: {dev-release-tarball: cf-tarball}
    params:
      <<: *bosh_params_fresh
  - task: upload-postgres-dev-releases-old
    file: postgres-release/ci/scripts/upload-dev-release-tarball/task.yml
    input_mapping: {dev-release-tarball: postgres-tarball}
    params:
      <<: *bosh_params_old
  - task: upload-cf-dev-releases-old
    file: postgres-release/ci/scripts/upload-dev-release-tarball/task.yml
    input_mapping: {dev-release-tarball: cf-tarball}
    params:
      <<: *bosh_params_old
  - task: upload-postgres-dev-releases-older
    file: postgres-release/ci/scripts/upload-dev-release-tarball/task.yml
    input_mapping: {dev-release-tarball: postgres-tarball}
    params:
      <<: *bosh_params_older
  - task: upload-cf-dev-releases-older
    file: postgres-release/ci/scripts/upload-dev-release-tarball/task.yml
    input_mapping: {dev-release-tarball: cf-tarball}
    params:
      <<: *bosh_params_older
